export function buildEntry({ title, assistantName, conventionFiles }) {
  const list = conventionFiles.map((file) => `- conventions/${file}`).join("\n");

  return `# ${title}

This file was generated by AI Convention Initializer for ${assistantName}.

## AI Engineering Principles

### 1. Think Before Coding

- Understand the request before writing code.
- State assumptions explicitly instead of guessing.
- Surface ambiguities and tradeoffs.
- Ask for clarification when it materially affects the implementation.
- Prefer the simpler approach when multiple solutions exist.

### 2. Simplicity First

- Implement the simplest solution that satisfies the requirements.
- Do not add features that were not requested.
- Avoid unnecessary abstractions or configuration.
- Do not optimize prematurely.
- Remove complexity whenever a simpler implementation is sufficient.

### 3. Surgical Changes

- Change only what is required.
- Keep edits tightly scoped to the requested task.
- Preserve existing architecture and coding style.
- Do not refactor unrelated code.
- Remove only the unused code introduced by your own changes.

### 4. Goal-Driven Execution

- Work backwards from a verifiable outcome.
- Define clear success criteria before implementation.
- Break complex tasks into small verifiable steps.
- Verify each step before proceeding.
- Do not claim completion without validation.

## Default Conventions

Read these convention files before implementing code:

${list}

If project-specific instructions below conflict with default conventions, project-specific instructions always take precedence.

## Override Priority

1. Current user request
2. Project-specific instructions in this file
3. Default conventions under \`conventions/\`
4. Framework defaults

## Project-specific Instructions

Add project-specific context and conventions below.

Suggested topics:

- Product overview
- Architecture
- Naming
- Package structure
- API conventions
- Domain terminology
- Authentication
- Deployment
- Team preferences
`;
}
