export function buildEntry({ title, assistantName, conventionFiles }) {
  const list = conventionFiles.map((file) => `- conventions/${file}`).join("\n");

  return `# ${title}

This file was generated by AI Convention Initializer for ${assistantName}.

## Default Conventions

Read these convention files before implementing code:

${list}

If project-specific instructions below conflict with default conventions, project-specific instructions always take precedence.

## Override Priority

1. Current user request
2. Project-specific instructions in this file
3. Default conventions under \`conventions/\`
4. Framework defaults

## Project-specific Instructions

Add project-specific context and conventions below.

Suggested topics:

- Product overview
- Architecture
- Naming
- Package structure
- API conventions
- Domain terminology
- Authentication
- Deployment
- Team preferences
`;
}
